name: Analyzers

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  analyse:
    runs-on: ubuntu-latest

    env:
      CXX: clang++

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: deps
      run: |
        sudo apt install -y meson clang clang-tidy

    - name: configure
      run: |
        meson setup build

    - name: examples & tests
      run: |
        meson compile -C build
        meson test -C build

    - name: clang-tidy
      run: |
        ninja -C build clang-tidy
