name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [gcc, clang]

    env:
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: deps
      run: |
        sudo apt install -y meson clang clang-tidy

    - name: configure
      run: |
        meson setup build

    - name: examples & tests
      run: |
        meson compile -C build
        meson test -C build
